version: 2
project_name: opentelemetry-operations-collector

snapshot:
  version_template: 1.4.0

env:
  - LD_FLAGS=-s -w
  - CGO_ENABLED=0 # TODO: CGO is not supported in goreleaser yet.
  - BUILD_FLAGS=-trimpath
  - GOWORK=off

builds:
  - id: rungmpcol-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: rungmpcol
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

  - id: rungmpcol-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: rungmpcol
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

nfpms:
  - package_name: rungmpcol
    contents:
      - src: rungmpcol.service
        dst: /lib/systemd/system/rungmpcol.service
      - src: rungmpcol.conf
        dst: /etc/rungmpcol/rungmpcol.conf
        type: config|noreplace
        file_info:
          mode: 0644
      - src: config.yaml
        dst: /etc/rungmpcol/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    ids:
      - rungmpcol-linux
    formats:
      - deb
      - rpm
    umask: 0
    maintainer: Google Cloud Platform <google@google.com> # something better than this
    description: The Cloud Run GMP Sidecar build of the OTel Collector
    license: Apache 2.0
