FROM golang:{{ .GoVersion }} as builder
WORKDIR /sidecar
COPY . .

RUN apt update && apt install -y make

WORKDIR /sidecar/run-gmp-sidecar
RUN make -f run-gmp-build.mk build-rungmp

FROM alpine:latest AS certs
RUN apk --update add ca-certificates

FROM scratch

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /sidecar/run-gmp-sidecar/rungmpcol /rungmpcol
COPY --from=builder /sidecar/run-gmp-sidecar/run-gmp-entrypoint /run-gmp-entrypoint

ENTRYPOINT ["/run-gmp-entrypoint"]
