# NOTE: File generated by distrogen. Do not manually edit.

include ./Makefile

ENTRYPOINT_BINARY_NAME = run-gmp-entrypoint
ENTRYPOINT_SRC = ./entrypoint.go
ENTRYPOINT_IMPORT_PATH = github.com/GoogleCloudPlatform/run-gmp-sidecar/confgenerator
ENTRYPOINT_LD_FLAGS := -X $(ENTRYPOINT_IMPORT_PATH).Version=$(VERSION)

.PHONY: build-rungmp
build-rungmp: build entrypoint-build

.PHONY: clean-rungmp
clean-rungmp: clean clean-entrypoint

.PHONY: entrypoint-build
entrypoint-build: clean-entrypoint $(ENTRYPOINT_BINARY_NAME)

$(ENTRYPOINT_BINARY_NAME):
	@echo "Building $(ENTRYPOINT_BINARY_NAME) from project root..."
	cd ../&& \
	GOWORK=off \
	CGO_ENABLED=$(COLLECTOR_CGO) \
	GOOS=$(TARGETOS) GOARCH=$(TARGETARCH) \
	$(if $(USE_GO_PROXY),GOPROXY=$(USE_GO_PROXY),) \
	$(GO_BIN) build \
		-buildvcs=$(COLLECTOR_BUILDVCS) \
		-tags=$(COLLECTOR_BUILD_TAGS) \
		--ldflags="-s -w $(ENTRYPOINT_LD_FLAGS)" \
		-o $(CURDIR)/$(ENTRYPOINT_BINARY_NAME) \
		$(ENTRYPOINT_SRC)

.PHONY: clean-entrypoint
clean-entrypoint:
	rm -f $(ENTRYPOINT_BINARY_NAME)
