type: googlemanagedprometheus
scope_name: otelcol/googlemanagedprometheus

status:
  class: exporter
  stability:
    beta: [metrics]
  distributions: [contrib, observiq]

tests:
  skip_lifecycle: true
  goleak:
    ignore:
      top:
        # See https://github.com/census-instrumentation/opencensus-go/issues/1191 for more information.
        - "go.opencensus.io/stats/view.(*worker).start"